### ISSUE TITLE
Crash (Cannot invoke "net.minecraft.item.ItemStack.func_190926_b()" because "target" is null)

### ISSUE THREAD

**Issue by aking4125** [Elite-Modding-Team/NaturaLegacy#4]
Hello, Upon replacing the original Natura with this updated fork. The game crashes upon starting. Using the original mod works.

There may be some other conflict here and probably something broken regarding the use of [Cleanroom](https://github.com/CleanroomMC/Cleanroom) here. Any ideas?

[crash-2024-10-10_15.05.45-client.txt](https://github.com/user-attachments/files/17333072/crash-2024-10-10_15.05.45-client.txt)

[2024-10-10-7.log.gz](https://github.com/user-attachments/files/17333078/2024-10-10-7.log.gz)

**Comment by IcarussOne** [comment]
The log mentions Tinkers' Construct and I see a lot of other mods installed here. Does this occur with just Natura Legacy installed?

**Comment by aking4125** [comment]
Yes. This crash occurs only with [NaturaLegacy](https://github.com/Elite-Modding-Team/NaturaLegacy) but using the original version of Natura. The game loads perfectly fine.

**Comment by ACGaming** [comment]
Since this is not occurring with just Tinkers' Construct and Natura Legacy, this is probably introduced by add-ons for Tinkers' Construct.

**Comment by aking4125** [comment]
> Since this is not occurring with just Tinkers' Construct and Natura Legacy, this is probably introduced by add-ons for Tinkers' Construct.

Yeah I figured there's sometype of conflict. Any ideas on what it could be based on the information given that could help narrow it down?

I'm gonna deepdive and see if I can identify which mod or combination is causing the barrier and report back my findings.

This may take sometime, if I find anything I'll post it here.

**Comment by ACGaming** [comment]
Try setting `Enable stick variants` to `true` inside Natura's config file `natura.cfg`.

**Comment by IcarussOne** [comment]
#12

**Comment by aking4125** [comment]
> Try setting `Enable stick variants` to `true` inside Natura's config file `natura.cfg`.

Yep that fixed it. Sorry for the late response. Thanks!
